# Site settings
title: non0
description: "non0 personal blog"
url:  "https://arnaudlhutereau.github.io/" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Arnaud L'hutereau"
  email: "firstname.lastname@gmail.com"
  url: "https://arnaudlhutereau.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/#
    - https://www.github.com/ArnaudLhutereau
    - https://www.linkedin.com/in/#
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: fr_FR

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never
